name: CI to generate
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

# Cancel in-progress runs in current workflow.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' || github.ref_name == 'main' }}
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: set up the Git client
        run: |
          git config --global user.email "35197703+imrushi@users.noreply.github.com"
          git config --global user.name "bot"
        shell: bash
      - name: Run a changelog script
        run: ./create_changelog.sh
      - name: commit the changes
        if: ${{ github.ref_name == 'main' || github.ref_type == 'tag' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          branch="$(date +%s)"
          git checkout -b "$branch" || true
          git add CHANGELOG.md || true
          git commit -m "autogen(docs): regenerate and update changelog" -m "[skip ci]" || true
          git pull origin main --rebase || true
          git push origin HEAD:main || true
        shell: bash